# Project: 通讯录系统
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 主函数.o
LINKOBJ  = 主函数.o
LIBS     = -L"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/lib" -L"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/include" -I"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/x86_64-w64-mingw32/include" -I"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/include" -I"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/x86_64-w64-mingw32/include" -I"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/LenovoSoftstore/Install/Dev_C__/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 通讯录系统.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

主函数.o: 主函数.cpp
	$(CPP) -c 主函数.cpp -o 主函数.o $(CXXFLAGS)
